/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAiAnalysRouteImport } from './routes/_authenticated/ai-analys'
import { Route as AuthenticatedAiImportRouteImport } from './routes/_authenticated/ai-import'
import { Route as AuthenticatedAnalyseraRouteImport } from './routes/_authenticated/analysera'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedEfterrapporterRouteImport } from './routes/_authenticated/efterrapporter'
import { Route as AuthenticatedEkonomiRouteImport } from './routes/_authenticated/ekonomi'
import { Route as AuthenticatedExperttipsRouteImport } from './routes/_authenticated/experttips'
import { Route as AuthenticatedHistorikRouteImport } from './routes/_authenticated/historik'
import { Route as AuthenticatedHistorikDubbletterRouteImport } from './routes/_authenticated/historik-dubbletter'
import { Route as AuthenticatedHistorikimportRouteImport } from './routes/_authenticated/historikimport'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated/installningar'
import { Route as AuthenticatedKommenteraRouteImport } from './routes/_authenticated/kommentera'
import { Route as AuthenticatedLarandeRouteImport } from './routes/_authenticated/larande'
import { Route as AuthenticatedMerRouteImport } from './routes/_authenticated/mer'
import { Route as AuthenticatedMinaRadRouteImport } from './routes/_authenticated/mina-rad'
import { Route as AuthenticatedOversiktRouteImport } from './routes/_authenticated/oversikt'
import { Route as AuthenticatedResultatRouteImport } from './routes/_authenticated/resultat'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedVeckansSpelRouteImport } from './routes/_authenticated/veckans-spel'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedOmgangarIndexRouteImport } from './routes/_authenticated/omgangar/index'
import { Route as AuthenticatedOmgangarRoundIdRouteImport } from './routes/_authenticated/omgangar/$roundId'
import { Route as ApiPublicAiImportRouteImport } from './routes/api/public/ai-import'
import { Route as ApiPublicHooksAutomationRouteImport } from './routes/api/public/hooks/automation'
import { Route as ApiPublicHooksExperttipsRouteImport } from './routes/api/public/hooks/experttips'
import { Route as ApiPublicHooksResultatV85RouteImport } from './routes/api/public/hooks/resultat-v85'
import { Route as ApiPublicHooksVeckansV85RouteImport } from './routes/api/public/hooks/veckans-v85'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAiAnalysRoute = AuthenticatedAiAnalysRouteImport.update({
  id: '/ai-analys',
  path: '/ai-analys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiImportRoute = AuthenticatedAiImportRouteImport.update({
  id: '/ai-import',
  path: '/ai-import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyseraRoute = AuthenticatedAnalyseraRouteImport.update({
  id: '/analysera',
  path: '/analysera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEfterrapporterRoute =
  AuthenticatedEfterrapporterRouteImport.update({
    id: '/efterrapporter',
    path: '/efterrapporter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEkonomiRoute = AuthenticatedEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperttipsRoute = AuthenticatedExperttipsRouteImport.update({
  id: '/experttips',
  path: '/experttips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorikRoute = AuthenticatedHistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorikDubbletterRoute =
  AuthenticatedHistorikDubbletterRouteImport.update({
    id: '/historik-dubbletter',
    path: '/historik-dubbletter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistorikimportRoute =
  AuthenticatedHistorikimportRouteImport.update({
    id: '/historikimport',
    path: '/historikimport',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKommenteraRoute = AuthenticatedKommenteraRouteImport.update({
  id: '/kommentera',
  path: '/kommentera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLarandeRoute = AuthenticatedLarandeRouteImport.update({
  id: '/larande',
  path: '/larande',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerRoute = AuthenticatedMerRouteImport.update({
  id: '/mer',
  path: '/mer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinaRadRoute = AuthenticatedMinaRadRouteImport.update({
  id: '/mina-rad',
  path: '/mina-rad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOversiktRoute = AuthenticatedOversiktRouteImport.update({
  id: '/oversikt',
  path: '/oversikt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultatRoute = AuthenticatedResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeckansSpelRoute =
  AuthenticatedVeckansSpelRouteImport.update({
    id: '/veckans-spel',
    path: '/veckans-spel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOmgangarIndexRoute =
  AuthenticatedOmgangarIndexRouteImport.update({
    id: '/omgangar/',
    path: '/omgangar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOmgangarRoundIdRoute =
  AuthenticatedOmgangarRoundIdRouteImport.update({
    id: '/omgangar/$roundId',
    path: '/omgangar/$roundId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAiImportRoute = ApiPublicAiImportRouteImport.update({
  id: '/api/public/ai-import',
  path: '/api/public/ai-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutomationRoute =
  ApiPublicHooksAutomationRouteImport.update({
    id: '/api/public/hooks/automation',
    path: '/api/public/hooks/automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExperttipsRoute =
  ApiPublicHooksExperttipsRouteImport.update({
    id: '/api/public/hooks/experttips',
    path: '/api/public/hooks/experttips',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResultatV85Route =
  ApiPublicHooksResultatV85RouteImport.update({
    id: '/api/public/hooks/resultat-v85',
    path: '/api/public/hooks/resultat-v85',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVeckansV85Route =
  ApiPublicHooksVeckansV85RouteImport.update({
    id: '/api/public/hooks/veckans-v85',
    path: '/api/public/hooks/veckans-v85',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-analys': typeof AuthenticatedAiAnalysRoute
  '/ai-import': typeof AuthenticatedAiImportRoute
  '/analysera': typeof AuthenticatedAnalyseraRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/efterrapporter': typeof AuthenticatedEfterrapporterRoute
  '/ekonomi': typeof AuthenticatedEkonomiRoute
  '/experttips': typeof AuthenticatedExperttipsRoute
  '/historik': typeof AuthenticatedHistorikRoute
  '/historik-dubbletter': typeof AuthenticatedHistorikDubbletterRoute
  '/historikimport': typeof AuthenticatedHistorikimportRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/kommentera': typeof AuthenticatedKommenteraRoute
  '/larande': typeof AuthenticatedLarandeRoute
  '/mer': typeof AuthenticatedMerRoute
  '/mina-rad': typeof AuthenticatedMinaRadRoute
  '/oversikt': typeof AuthenticatedOversiktRoute
  '/resultat': typeof AuthenticatedResultatRoute
  '/system': typeof AuthenticatedSystemRoute
  '/veckans-spel': typeof AuthenticatedVeckansSpelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/omgangar/$roundId': typeof AuthenticatedOmgangarRoundIdRoute
  '/api/public/ai-import': typeof ApiPublicAiImportRoute
  '/omgangar/': typeof AuthenticatedOmgangarIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/experttips': typeof ApiPublicHooksExperttipsRoute
  '/api/public/hooks/resultat-v85': typeof ApiPublicHooksResultatV85Route
  '/api/public/hooks/veckans-v85': typeof ApiPublicHooksVeckansV85Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-analys': typeof AuthenticatedAiAnalysRoute
  '/ai-import': typeof AuthenticatedAiImportRoute
  '/analysera': typeof AuthenticatedAnalyseraRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/efterrapporter': typeof AuthenticatedEfterrapporterRoute
  '/ekonomi': typeof AuthenticatedEkonomiRoute
  '/experttips': typeof AuthenticatedExperttipsRoute
  '/historik': typeof AuthenticatedHistorikRoute
  '/historik-dubbletter': typeof AuthenticatedHistorikDubbletterRoute
  '/historikimport': typeof AuthenticatedHistorikimportRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/kommentera': typeof AuthenticatedKommenteraRoute
  '/larande': typeof AuthenticatedLarandeRoute
  '/mer': typeof AuthenticatedMerRoute
  '/mina-rad': typeof AuthenticatedMinaRadRoute
  '/oversikt': typeof AuthenticatedOversiktRoute
  '/resultat': typeof AuthenticatedResultatRoute
  '/system': typeof AuthenticatedSystemRoute
  '/veckans-spel': typeof AuthenticatedVeckansSpelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/omgangar/$roundId': typeof AuthenticatedOmgangarRoundIdRoute
  '/api/public/ai-import': typeof ApiPublicAiImportRoute
  '/omgangar': typeof AuthenticatedOmgangarIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/experttips': typeof ApiPublicHooksExperttipsRoute
  '/api/public/hooks/resultat-v85': typeof ApiPublicHooksResultatV85Route
  '/api/public/hooks/veckans-v85': typeof ApiPublicHooksVeckansV85Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ai-analys': typeof AuthenticatedAiAnalysRoute
  '/_authenticated/ai-import': typeof AuthenticatedAiImportRoute
  '/_authenticated/analysera': typeof AuthenticatedAnalyseraRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/efterrapporter': typeof AuthenticatedEfterrapporterRoute
  '/_authenticated/ekonomi': typeof AuthenticatedEkonomiRoute
  '/_authenticated/experttips': typeof AuthenticatedExperttipsRoute
  '/_authenticated/historik': typeof AuthenticatedHistorikRoute
  '/_authenticated/historik-dubbletter': typeof AuthenticatedHistorikDubbletterRoute
  '/_authenticated/historikimport': typeof AuthenticatedHistorikimportRoute
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/_authenticated/kommentera': typeof AuthenticatedKommenteraRoute
  '/_authenticated/larande': typeof AuthenticatedLarandeRoute
  '/_authenticated/mer': typeof AuthenticatedMerRoute
  '/_authenticated/mina-rad': typeof AuthenticatedMinaRadRoute
  '/_authenticated/oversikt': typeof AuthenticatedOversiktRoute
  '/_authenticated/resultat': typeof AuthenticatedResultatRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/veckans-spel': typeof AuthenticatedVeckansSpelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/omgangar/$roundId': typeof AuthenticatedOmgangarRoundIdRoute
  '/api/public/ai-import': typeof ApiPublicAiImportRoute
  '/_authenticated/omgangar/': typeof AuthenticatedOmgangarIndexRoute
  '/api/public/hooks/automation': typeof ApiPublicHooksAutomationRoute
  '/api/public/hooks/experttips': typeof ApiPublicHooksExperttipsRoute
  '/api/public/hooks/resultat-v85': typeof ApiPublicHooksResultatV85Route
  '/api/public/hooks/veckans-v85': typeof ApiPublicHooksVeckansV85Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-analys'
    | '/ai-import'
    | '/analysera'
    | '/automation'
    | '/efterrapporter'
    | '/ekonomi'
    | '/experttips'
    | '/historik'
    | '/historik-dubbletter'
    | '/historikimport'
    | '/installningar'
    | '/kommentera'
    | '/larande'
    | '/mer'
    | '/mina-rad'
    | '/oversikt'
    | '/resultat'
    | '/system'
    | '/veckans-spel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/omgangar/$roundId'
    | '/api/public/ai-import'
    | '/omgangar/'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/experttips'
    | '/api/public/hooks/resultat-v85'
    | '/api/public/hooks/veckans-v85'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-analys'
    | '/ai-import'
    | '/analysera'
    | '/automation'
    | '/efterrapporter'
    | '/ekonomi'
    | '/experttips'
    | '/historik'
    | '/historik-dubbletter'
    | '/historikimport'
    | '/installningar'
    | '/kommentera'
    | '/larande'
    | '/mer'
    | '/mina-rad'
    | '/oversikt'
    | '/resultat'
    | '/system'
    | '/veckans-spel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/omgangar/$roundId'
    | '/api/public/ai-import'
    | '/omgangar'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/experttips'
    | '/api/public/hooks/resultat-v85'
    | '/api/public/hooks/veckans-v85'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ai-analys'
    | '/_authenticated/ai-import'
    | '/_authenticated/analysera'
    | '/_authenticated/automation'
    | '/_authenticated/efterrapporter'
    | '/_authenticated/ekonomi'
    | '/_authenticated/experttips'
    | '/_authenticated/historik'
    | '/_authenticated/historik-dubbletter'
    | '/_authenticated/historikimport'
    | '/_authenticated/installningar'
    | '/_authenticated/kommentera'
    | '/_authenticated/larande'
    | '/_authenticated/mer'
    | '/_authenticated/mina-rad'
    | '/_authenticated/oversikt'
    | '/_authenticated/resultat'
    | '/_authenticated/system'
    | '/_authenticated/veckans-spel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/omgangar/$roundId'
    | '/api/public/ai-import'
    | '/_authenticated/omgangar/'
    | '/api/public/hooks/automation'
    | '/api/public/hooks/experttips'
    | '/api/public/hooks/resultat-v85'
    | '/api/public/hooks/veckans-v85'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAiImportRoute: typeof ApiPublicAiImportRoute
  ApiPublicHooksAutomationRoute: typeof ApiPublicHooksAutomationRoute
  ApiPublicHooksExperttipsRoute: typeof ApiPublicHooksExperttipsRoute
  ApiPublicHooksResultatV85Route: typeof ApiPublicHooksResultatV85Route
  ApiPublicHooksVeckansV85Route: typeof ApiPublicHooksVeckansV85Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-analys': {
      id: '/_authenticated/ai-analys'
      path: '/ai-analys'
      fullPath: '/ai-analys'
      preLoaderRoute: typeof AuthenticatedAiAnalysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-import': {
      id: '/_authenticated/ai-import'
      path: '/ai-import'
      fullPath: '/ai-import'
      preLoaderRoute: typeof AuthenticatedAiImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysera': {
      id: '/_authenticated/analysera'
      path: '/analysera'
      fullPath: '/analysera'
      preLoaderRoute: typeof AuthenticatedAnalyseraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/efterrapporter': {
      id: '/_authenticated/efterrapporter'
      path: '/efterrapporter'
      fullPath: '/efterrapporter'
      preLoaderRoute: typeof AuthenticatedEfterrapporterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ekonomi': {
      id: '/_authenticated/ekonomi'
      path: '/ekonomi'
      fullPath: '/ekonomi'
      preLoaderRoute: typeof AuthenticatedEkonomiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experttips': {
      id: '/_authenticated/experttips'
      path: '/experttips'
      fullPath: '/experttips'
      preLoaderRoute: typeof AuthenticatedExperttipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historik': {
      id: '/_authenticated/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof AuthenticatedHistorikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historik-dubbletter': {
      id: '/_authenticated/historik-dubbletter'
      path: '/historik-dubbletter'
      fullPath: '/historik-dubbletter'
      preLoaderRoute: typeof AuthenticatedHistorikDubbletterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historikimport': {
      id: '/_authenticated/historikimport'
      path: '/historikimport'
      fullPath: '/historikimport'
      preLoaderRoute: typeof AuthenticatedHistorikimportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kommentera': {
      id: '/_authenticated/kommentera'
      path: '/kommentera'
      fullPath: '/kommentera'
      preLoaderRoute: typeof AuthenticatedKommenteraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/larande': {
      id: '/_authenticated/larande'
      path: '/larande'
      fullPath: '/larande'
      preLoaderRoute: typeof AuthenticatedLarandeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mer': {
      id: '/_authenticated/mer'
      path: '/mer'
      fullPath: '/mer'
      preLoaderRoute: typeof AuthenticatedMerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mina-rad': {
      id: '/_authenticated/mina-rad'
      path: '/mina-rad'
      fullPath: '/mina-rad'
      preLoaderRoute: typeof AuthenticatedMinaRadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oversikt': {
      id: '/_authenticated/oversikt'
      path: '/oversikt'
      fullPath: '/oversikt'
      preLoaderRoute: typeof AuthenticatedOversiktRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultat': {
      id: '/_authenticated/resultat'
      path: '/resultat'
      fullPath: '/resultat'
      preLoaderRoute: typeof AuthenticatedResultatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veckans-spel': {
      id: '/_authenticated/veckans-spel'
      path: '/veckans-spel'
      fullPath: '/veckans-spel'
      preLoaderRoute: typeof AuthenticatedVeckansSpelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/omgangar/': {
      id: '/_authenticated/omgangar/'
      path: '/omgangar'
      fullPath: '/omgangar/'
      preLoaderRoute: typeof AuthenticatedOmgangarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/omgangar/$roundId': {
      id: '/_authenticated/omgangar/$roundId'
      path: '/omgangar/$roundId'
      fullPath: '/omgangar/$roundId'
      preLoaderRoute: typeof AuthenticatedOmgangarRoundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ai-import': {
      id: '/api/public/ai-import'
      path: '/api/public/ai-import'
      fullPath: '/api/public/ai-import'
      preLoaderRoute: typeof ApiPublicAiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation': {
      id: '/api/public/hooks/automation'
      path: '/api/public/hooks/automation'
      fullPath: '/api/public/hooks/automation'
      preLoaderRoute: typeof ApiPublicHooksAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/experttips': {
      id: '/api/public/hooks/experttips'
      path: '/api/public/hooks/experttips'
      fullPath: '/api/public/hooks/experttips'
      preLoaderRoute: typeof ApiPublicHooksExperttipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resultat-v85': {
      id: '/api/public/hooks/resultat-v85'
      path: '/api/public/hooks/resultat-v85'
      fullPath: '/api/public/hooks/resultat-v85'
      preLoaderRoute: typeof ApiPublicHooksResultatV85RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/veckans-v85': {
      id: '/api/public/hooks/veckans-v85'
      path: '/api/public/hooks/veckans-v85'
      fullPath: '/api/public/hooks/veckans-v85'
      preLoaderRoute: typeof ApiPublicHooksVeckansV85RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAnalysRoute: typeof AuthenticatedAiAnalysRoute
  AuthenticatedAiImportRoute: typeof AuthenticatedAiImportRoute
  AuthenticatedAnalyseraRoute: typeof AuthenticatedAnalyseraRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedEfterrapporterRoute: typeof AuthenticatedEfterrapporterRoute
  AuthenticatedEkonomiRoute: typeof AuthenticatedEkonomiRoute
  AuthenticatedExperttipsRoute: typeof AuthenticatedExperttipsRoute
  AuthenticatedHistorikRoute: typeof AuthenticatedHistorikRoute
  AuthenticatedHistorikDubbletterRoute: typeof AuthenticatedHistorikDubbletterRoute
  AuthenticatedHistorikimportRoute: typeof AuthenticatedHistorikimportRoute
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedKommenteraRoute: typeof AuthenticatedKommenteraRoute
  AuthenticatedLarandeRoute: typeof AuthenticatedLarandeRoute
  AuthenticatedMerRoute: typeof AuthenticatedMerRoute
  AuthenticatedMinaRadRoute: typeof AuthenticatedMinaRadRoute
  AuthenticatedOversiktRoute: typeof AuthenticatedOversiktRoute
  AuthenticatedResultatRoute: typeof AuthenticatedResultatRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedVeckansSpelRoute: typeof AuthenticatedVeckansSpelRoute
  AuthenticatedOmgangarRoundIdRoute: typeof AuthenticatedOmgangarRoundIdRoute
  AuthenticatedOmgangarIndexRoute: typeof AuthenticatedOmgangarIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAnalysRoute: AuthenticatedAiAnalysRoute,
  AuthenticatedAiImportRoute: AuthenticatedAiImportRoute,
  AuthenticatedAnalyseraRoute: AuthenticatedAnalyseraRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedEfterrapporterRoute: AuthenticatedEfterrapporterRoute,
  AuthenticatedEkonomiRoute: AuthenticatedEkonomiRoute,
  AuthenticatedExperttipsRoute: AuthenticatedExperttipsRoute,
  AuthenticatedHistorikRoute: AuthenticatedHistorikRoute,
  AuthenticatedHistorikDubbletterRoute: AuthenticatedHistorikDubbletterRoute,
  AuthenticatedHistorikimportRoute: AuthenticatedHistorikimportRoute,
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedKommenteraRoute: AuthenticatedKommenteraRoute,
  AuthenticatedLarandeRoute: AuthenticatedLarandeRoute,
  AuthenticatedMerRoute: AuthenticatedMerRoute,
  AuthenticatedMinaRadRoute: AuthenticatedMinaRadRoute,
  AuthenticatedOversiktRoute: AuthenticatedOversiktRoute,
  AuthenticatedResultatRoute: AuthenticatedResultatRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedVeckansSpelRoute: AuthenticatedVeckansSpelRoute,
  AuthenticatedOmgangarRoundIdRoute: AuthenticatedOmgangarRoundIdRoute,
  AuthenticatedOmgangarIndexRoute: AuthenticatedOmgangarIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAiImportRoute: ApiPublicAiImportRoute,
  ApiPublicHooksAutomationRoute: ApiPublicHooksAutomationRoute,
  ApiPublicHooksExperttipsRoute: ApiPublicHooksExperttipsRoute,
  ApiPublicHooksResultatV85Route: ApiPublicHooksResultatV85Route,
  ApiPublicHooksVeckansV85Route: ApiPublicHooksVeckansV85Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
